// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IStrategy
 * @notice Interface for vault strategies that manage deposited funds
 * @dev Strategies receive funds from BloomStrategyVault and generate yield
 */
interface IStrategy {
    /**
     * @notice Deposit funds into the strategy
     * @param amount Amount of asset tokens to deposit
     * @dev Called by vault when users deposit. Strategy should pull funds from vault.
     */
    function deposit(uint256 amount) external;

    /**
     * @notice Withdraw funds from the strategy
     * @param amount Amount of asset tokens to withdraw
     * @dev Called by vault when users withdraw. Strategy should return funds to vault.
     *      May return less than requested if funds are deployed (queued withdrawal).
     */
    function withdraw(uint256 amount) external;

    /**
     * @notice Claim accumulated rewards/profits
     * @param recipient Address to receive the rewards
     * @return rewardAmount Amount of rewards claimed and sent to recipient
     * @dev Called by vault during harvest. Returns profit generated by strategy.
     */
    function claimRewards(address recipient) external returns (uint256 rewardAmount);

    /**
     * @notice Get total assets managed by this strategy
     * @return Total value of assets in the strategy (principal + unrealized profit)
     * @dev Used by vault for share pricing and totalAssets calculation
     */
    function totalAssets() external view returns (uint256);
}

